#FROM jenkins/jenkins:2.347-jdk11
FROM jenkins/jenkins:lts-jdk11

USER jenkins
RUN jenkins-plugin-cli --plugins blueocean:1.27.16 build-timestamp timestamper pollscm github-api

USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

COPY ./requirements.txt requirements.txt

RUN apt update && \
    apt install -y python3 python3-pip

RUN apt-get update && apt-get install -y \
build-essential \
libssl-dev \
zlib1g-dev \
libbz2-dev \
libreadline-dev \
libsqlite3-dev \
wget \
curl \
llvm \
libncurses5-dev \
libncursesw5-dev \
xz-utils \
tk-dev \
libffi-dev \
liblzma-dev \
python3-openssl \
git && \
rm -rf /var/lib/apt/lists/*

# Instala o pyenv no diretório root (pode ser no /opt também)
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"

RUN curl https://pyenv.run | bash

# Adiciona os shims ao PATH
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"

# Instala versão específica do Python
RUN pyenv install 3.10.18 && pyenv global 3.10.18

RUN pip install -r requirements.txt

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
